spring.application.name=clone

server.port=8086
spring.datasource.url=jdbc:mysql://localhost:3306/airbnb
spring.datasource.username=root
spring.datasource.password=ASIF169@hasan


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey="yoiey7942uytfvb2cnk43soiu67hbv2536nmcscscxlsc3458sscdcoeiorutncmbsgywernaklwe"
